//! Plugin marketplace service — RFC 015.
//!
//! This is the layer above the existing plugin host (RFC 007). It manages:
//! - marketplace lifecycle (Listed → Installing → Installed → EnabledForProject → Uninstalled)
//! - per-project plugin enablement with tool/signal allowlists
//! - credential wizard flow
//! - bundled catalog loading
//!
//! There is NO `Connected` state and NO `POST /v1/plugins/:id/connect` endpoint.
//! Process instances are managed by the plugin host, not the marketplace.

use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use cairn_domain::contexts::{PluginCategory, SignalCaptureOverride, VisibilityContext};
use cairn_domain::ids::{CredentialId, OperatorId, RunId, SignalId};
use cairn_domain::tenancy::ProjectKey;
use cairn_plugin_catalog::CatalogEntry;
use serde::{Deserialize, Serialize};

/// Opaque credential value — the encrypted/raw value provided by the operator.
/// RFC 015 §Commands specifies `CredentialValue`; currently a String wrapper.
pub type CredentialValue = String;

/// Graph node identifier — matches cairn-graph's GraphNode.node_id type.
pub type GraphNodeId = String;

// ── Plugin Descriptor (RFC 015 §"Plugin Descriptor") ─────────────────────────

/// Marketplace metadata wrapping the plugin manifest.
/// The manifest describes the plugin process; the descriptor wraps it
/// with discovery, credential, and health-check metadata for the marketplace.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PluginDescriptor {
    /// Unique plugin identifier (must be unique per tenant).
    pub id: String,
    /// Human-readable plugin name.
    pub name: String,
    /// Plugin version string.
    pub version: String,
    /// Short description for the marketplace view.
    pub description: Option<String>,
    /// Marketplace filter category.
    pub category: PluginCategory,
    /// Icon URL displayed in marketplace view.
    pub icon_url: Option<String>,
    /// Vendor name ("GitHub", "Slack", "Custom").
    pub vendor: String,
    /// Binary command to spawn the plugin process.
    pub command: Vec<String>,
    /// Declared tool names this plugin provides.
    pub tools: Vec<String>,
    /// Declared signal source types this plugin emits.
    pub signal_sources: Vec<String>,
    /// Declared channel names this plugin can deliver to.
    pub channels: Vec<String>,
    /// Credentials the operator must provide (drives the wizard).
    pub required_credentials: Vec<CredentialSpec>,
    /// Declared network egress endpoints (stored+displayed in v1, NOT enforced).
    pub required_network_egress: Vec<String>,
    /// Optional health check for install/verify time.
    pub post_install_health_check: Option<HealthCheckSpec>,
    /// Where this descriptor came from.
    pub source: DescriptorSource,
    /// Download URL for the plugin binary (if from bundled catalog or remote).
    pub download_url: Option<String>,
    /// Whether this plugin declares any SignalSource capabilities
    /// (drives eager vs lazy spawn policy).
    pub has_signal_source: bool,
}

/// A credential the plugin requires, driving the credential wizard.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CredentialSpec {
    /// Internal key name (e.g. "github_app_private_key").
    pub key: String,
    /// Human-readable label for the wizard (e.g. "GitHub App Private Key").
    pub display_name: String,
    /// What kind of credential this is.
    pub kind: CredentialKind,
    /// URL with instructions for obtaining this credential.
    pub help_url: Option<String>,
    /// Optional pre-store validation.
    pub validation: Option<CredentialValidation>,
    /// The scope at which this credential is stored.
    pub scope: CredentialScopeHint,
    /// Whether this credential is auto-generated by cairn (e.g. webhook secrets).
    #[serde(default)]
    pub generated: bool,
}

/// Kind of credential.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CredentialKind {
    OAuth2,
    ApiKey,
    AppInstallation,
    BasicAuth,
}

/// Optional validation to run before storing a credential.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CredentialValidation {
    /// Call a URL and check for a 200 response.
    HttpCheck { url_template: String },
    /// Match a regex pattern.
    RegexMatch { pattern: String },
}

/// Scope hint for credential storage.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CredentialScopeHint {
    Tenant,
    Workspace,
    Project,
}

/// Health check specification for install/verify time.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct HealthCheckSpec {
    /// RPC method on the plugin that proves connectivity.
    pub method: String,
    /// Hard timeout in milliseconds.
    pub timeout_ms: u64,
    /// JSON value that the response must match for success.
    pub success_criteria: serde_json::Value,
}

// ── Marketplace State ────────────────────────────────────────────────────────

/// Lifecycle state of a plugin in the marketplace (tenant-scoped).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MarketplaceState {
    Listed,
    Installing,
    Installed,
    InstallationFailed { reason: String },
    Uninstalled,
}

/// Where a plugin descriptor came from.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DescriptorSource {
    BundledCatalog,
    LocalFile { path: String },
    RemoteUrl { url: String },
}

/// Credential scope key — derived from credential IDs bound to an enablement.
/// Process instances are keyed 1:1 with credential scope keys.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CredentialScopeKey(pub String);

/// Reason a process instance became ready.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InstanceReadyReason {
    EagerSignalSource,
    LazyFirstInvocation,
    Restart,
}

/// Reason a process instance stopped.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InstanceStoppedReason {
    Drained,
    Failed { details: String },
    Uninstalled,
}

/// Outcome of an ephemeral credential verification.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationOutcome {
    Ok,
    Failed { reason: String },
}

// ── Marketplace Commands (RFC 015 §Commands) ────────────────────────────────

/// Commands handled by the marketplace service.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "command", rename_all = "snake_case")]
pub enum MarketplaceCommand {
    InstallPlugin {
        plugin_id: String,
        initiated_by: OperatorId,
    },
    ProvidePluginCredentials {
        plugin_id: String,
        credentials: Vec<(String, CredentialValue)>,
        provided_by: OperatorId,
    },
    VerifyPluginCredentials {
        plugin_id: String,
        credential_scope_key: Option<CredentialScopeKey>,
        verified_by: OperatorId,
    },
    EnablePluginForProject {
        plugin_id: String,
        project: ProjectKey,
        tool_allowlist: Option<Vec<String>>,
        signal_allowlist: Option<Vec<String>>,
        signal_capture_override: Option<SignalCaptureOverride>,
        enabled_by: OperatorId,
    },
    DisablePluginForProject {
        plugin_id: String,
        project: ProjectKey,
        disabled_by: OperatorId,
    },
    UninstallPlugin {
        plugin_id: String,
        uninstalled_by: OperatorId,
    },
}

// ── Marketplace Events (RFC 015 §Events) ────────────────────────────────────

/// Events emitted by the marketplace service.
/// These will be integrated into `RuntimeEvent` in cairn-domain once
/// the event structs are wired in.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "event", rename_all = "snake_case")]
pub enum MarketplaceEvent {
    PluginListed {
        plugin_id: String,
        source: DescriptorSource,
        listed_at: u64,
    },
    PluginInstallationStarted {
        plugin_id: String,
        initiated_by: OperatorId,
        started_at: u64,
    },
    PluginInstalled {
        plugin_id: String,
        manifest_hash: String,
        at: u64,
    },
    PluginInstallationFailed {
        plugin_id: String,
        reason: String,
        at: u64,
    },
    PluginCredentialsProvided {
        plugin_id: String,
        credential_ids: Vec<CredentialId>,
        provided_by: OperatorId,
        at: u64,
    },
    PluginInstanceReady {
        plugin_id: String,
        credential_scope_key: CredentialScopeKey,
        reason: InstanceReadyReason,
        at: u64,
    },
    PluginInstanceStopped {
        plugin_id: String,
        credential_scope_key: CredentialScopeKey,
        reason: InstanceStoppedReason,
        at: u64,
    },
    PluginCredentialsVerified {
        plugin_id: String,
        credential_scope_key: CredentialScopeKey,
        outcome: VerificationOutcome,
        verified_by: OperatorId,
        at: u64,
    },
    PluginEnabledForProject {
        plugin_id: String,
        project: ProjectKey,
        enabled_by: OperatorId,
        tool_allowlist: Option<Vec<String>>,
        signal_allowlist: Option<Vec<String>>,
        signal_capture_override: Option<SignalCaptureOverride>,
        at: u64,
    },
    PluginDisabledForProject {
        plugin_id: String,
        project: ProjectKey,
        disabled_by: OperatorId,
        at: u64,
    },
    PluginUninstalled {
        plugin_id: String,
        uninstalled_by: OperatorId,
        credentials_revoked: Vec<CredentialId>,
        at: u64,
    },
    SignalProjectedToGraph {
        signal_id: SignalId,
        plugin_id: String,
        project: ProjectKey,
        node_id: GraphNodeId,
        at: u64,
    },
    SignalIngestedToMemory {
        signal_id: SignalId,
        plugin_id: String,
        project: ProjectKey,
        source_id: String,
        chunks_created: u32,
        at: u64,
    },
}

// ── Per-Plugin Marketplace Record ────────────────────────────────────────────

/// In-memory projection of a plugin's marketplace state (tenant-scoped).
#[derive(Clone, Debug)]
pub struct MarketplaceRecord {
    pub plugin_id: String,
    pub state: MarketplaceState,
    pub descriptor: PluginDescriptor,
    pub manifest_hash: Option<String>,
    pub credential_ids: Vec<CredentialId>,
    pub listed_at: u64,
    pub installed_at: Option<u64>,
}

/// Per-project plugin enablement record (project-scoped).
#[derive(Clone, Debug)]
pub struct PluginEnablement {
    pub plugin_id: String,
    pub project: ProjectKey,
    pub enabled: bool,
    pub enabled_at: u64,
    pub enabled_by: OperatorId,
    pub tool_allowlist: Option<Vec<String>>,
    pub signal_allowlist: Option<Vec<String>>,
    pub signal_capture_override: Option<SignalCaptureOverride>,
}

// ── MarketplaceService ──────────────────────────────────────────────────────

/// The marketplace service sits above the plugin host and manages the
/// discover → install → credential → enable → disable → uninstall lifecycle.
pub struct MarketplaceService<S> {
    _store: Arc<S>,
    /// Plugin marketplace records, keyed by plugin_id.
    records: HashMap<String, MarketplaceRecord>,
    /// Per-project enablements, keyed by (plugin_id, project).
    enablements: HashMap<(String, ProjectKey), PluginEnablement>,
}

fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

impl<S> MarketplaceService<S> {
    pub fn new(store: Arc<S>) -> Self {
        Self {
            _store: store,
            records: HashMap::new(),
            enablements: HashMap::new(),
        }
    }

    /// Process a marketplace command and return the resulting events.
    pub fn handle_command(
        &mut self,
        command: MarketplaceCommand,
    ) -> Result<Vec<MarketplaceEvent>, MarketplaceError> {
        match command {
            MarketplaceCommand::InstallPlugin {
                plugin_id,
                initiated_by,
            } => self.handle_install(plugin_id, initiated_by),

            MarketplaceCommand::ProvidePluginCredentials {
                plugin_id,
                credentials,
                provided_by,
            } => self.handle_provide_credentials(plugin_id, credentials, provided_by),

            MarketplaceCommand::VerifyPluginCredentials {
                plugin_id,
                credential_scope_key,
                verified_by,
            } => self.handle_verify_credentials(plugin_id, credential_scope_key, verified_by),

            MarketplaceCommand::EnablePluginForProject {
                plugin_id,
                project,
                tool_allowlist,
                signal_allowlist,
                signal_capture_override,
                enabled_by,
            } => self.handle_enable(
                plugin_id,
                project,
                tool_allowlist,
                signal_allowlist,
                signal_capture_override,
                enabled_by,
            ),

            MarketplaceCommand::DisablePluginForProject {
                plugin_id,
                project,
                disabled_by,
            } => self.handle_disable(plugin_id, project, disabled_by),

            MarketplaceCommand::UninstallPlugin {
                plugin_id,
                uninstalled_by,
            } => self.handle_uninstall(plugin_id, uninstalled_by),
        }
    }

    /// Register a plugin from the catalog as Listed.
    pub fn list_plugin(&mut self, descriptor: PluginDescriptor) -> MarketplaceEvent {
        let now = now_ms();
        let plugin_id = descriptor.id.clone();
        let source = descriptor.source.clone();
        let record = MarketplaceRecord {
            plugin_id: plugin_id.clone(),
            state: MarketplaceState::Listed,
            descriptor,
            manifest_hash: None,
            credential_ids: Vec::new(),
            listed_at: now,
            installed_at: None,
        };
        self.records.insert(plugin_id.clone(), record);

        MarketplaceEvent::PluginListed {
            plugin_id,
            source,
            listed_at: now,
        }
    }

    /// Query: list all known plugin descriptors.
    pub fn list_all_records(&self) -> Vec<&MarketplaceRecord> {
        self.records.values().collect()
    }

    /// Load the bundled catalog at startup. Returns PluginListed events.
    pub fn load_bundled_catalog(&mut self) -> Vec<MarketplaceEvent> {
        let entries = match cairn_plugin_catalog::load_bundled_catalog() {
            Ok(entries) => entries,
            Err(_) => return Vec::new(),
        };

        // Collect new descriptors first to avoid borrow conflict.
        let new_descriptors: Vec<PluginDescriptor> = entries
            .into_iter()
            .filter(|e| !self.records.contains_key(&e.id))
            .map(catalog_entry_to_descriptor)
            .collect();

        new_descriptors
            .into_iter()
            .map(|desc| self.list_plugin(desc))
            .collect()
    }

    /// Query: is a plugin installed and available?
    pub fn get_record(&self, plugin_id: &str) -> Option<&MarketplaceRecord> {
        self.records.get(plugin_id)
    }

    /// Query: is a plugin enabled for a project?
    pub fn get_enablement(
        &self,
        plugin_id: &str,
        project: &ProjectKey,
    ) -> Option<&PluginEnablement> {
        self.enablements
            .get(&(plugin_id.to_string(), project.clone()))
    }

    /// Query: list all enablements for a project.
    pub fn enablements_for_project(&self, project: &ProjectKey) -> Vec<&PluginEnablement> {
        self.enablements
            .values()
            .filter(|e| &e.project == project && e.enabled)
            .collect()
    }

    /// Build a VisibilityContext for a run in a project.
    ///
    /// This is used by prompt building and tool_search to filter tools
    /// to only those from plugins enabled for the project.
    pub fn build_visibility_context(
        &self,
        project: &ProjectKey,
        run_id: Option<RunId>,
    ) -> VisibilityContext {
        let enablements = self.enablements_for_project(project);

        let enabled_plugins: HashSet<String> =
            enablements.iter().map(|e| e.plugin_id.clone()).collect();

        let allowlisted_tools: HashMap<String, Option<HashSet<String>>> = enablements
            .iter()
            .map(|e| {
                let tools = e
                    .tool_allowlist
                    .as_ref()
                    .map(|list| list.iter().cloned().collect::<HashSet<String>>());
                (e.plugin_id.clone(), tools)
            })
            .collect();

        VisibilityContext {
            project: project.clone(),
            run_id,
            enabled_plugins,
            allowlisted_tools,
            // RFC 029: populated by `build_visibility_context_for_run` at
            // run-start time, once the resolved knowledge provider is known.
            // The legacy entry point used by project-level queries leaves
            // this `None`; callers that need `is_tool_visible` gating on
            // `memory_store` must go through the *_for_run helper.
            resolved_knowledge_provider: None,
        }
    }

    /// RFC 029: run-scoped variant of [`build_visibility_context`] that
    /// also resolves the project's knowledge-provider snapshot. The caller
    /// supplies the snapshot — typically derived from the latest
    /// `KnowledgeProviderConfigured` event plus the plugin host's cached
    /// handshake for a `plugin:<id>` ref — because the marketplace service
    /// has no visibility into the plugin host.
    ///
    /// When `None` is passed, behaviour matches [`build_visibility_context`]
    /// (every built-in stays visible). Use this variant on the run-start
    /// path so `memory_store` is hidden from the prompt for projects on a
    /// read-only knowledge provider.
    pub fn build_visibility_context_for_run(
        &self,
        project: &ProjectKey,
        run_id: RunId,
        resolved_knowledge_provider: Option<cairn_domain::events::ResolvedProviderSnapshot>,
    ) -> VisibilityContext {
        let mut ctx = self.build_visibility_context(project, Some(run_id));
        ctx.resolved_knowledge_provider = resolved_knowledge_provider;
        ctx
    }

    // ── Command Handlers ─────────────────────────────────────────────────

    fn handle_install(
        &mut self,
        plugin_id: String,
        initiated_by: OperatorId,
    ) -> Result<Vec<MarketplaceEvent>, MarketplaceError> {
        let record = self
            .records
            .get(&plugin_id)
            .ok_or_else(|| MarketplaceError::PluginNotFound(plugin_id.clone()))?;

        // RFC 015 Non-Goals: reject manifests declaring eval_scorer capability.
        if record.descriptor.category == PluginCategory::EvalScorer {
            return Err(MarketplaceError::EvalScorerReserved);
        }

        match &record.state {
            MarketplaceState::Listed | MarketplaceState::InstallationFailed { .. } => {}
            MarketplaceState::Uninstalled => {}
            _ => {
                return Err(MarketplaceError::InvalidTransition {
                    plugin_id: plugin_id.clone(),
                    from: format!("{:?}", record.state),
                    to: "Installing".to_string(),
                });
            }
        }

        let now = now_ms();
        let started = MarketplaceEvent::PluginInstallationStarted {
            plugin_id: plugin_id.clone(),
            initiated_by,
            started_at: now,
        };

        // Transition to Installing
        if let Some(record) = self.records.get_mut(&plugin_id) {
            record.state = MarketplaceState::Installing;
        }

        // For now, immediately mark as installed (real impl will do async download)
        let installed = MarketplaceEvent::PluginInstalled {
            plugin_id: plugin_id.clone(),
            manifest_hash: String::new(), // populated during real install
            at: now,
        };

        if let Some(record) = self.records.get_mut(&plugin_id) {
            record.state = MarketplaceState::Installed;
            record.installed_at = Some(now);
        }

        Ok(vec![started, installed])
    }

    fn handle_provide_credentials(
        &mut self,
        plugin_id: String,
        _credentials: Vec<(String, CredentialValue)>,
        provided_by: OperatorId,
    ) -> Result<Vec<MarketplaceEvent>, MarketplaceError> {
        let record = self
            .records
            .get(&plugin_id)
            .ok_or_else(|| MarketplaceError::PluginNotFound(plugin_id.clone()))?;

        if record.state != MarketplaceState::Installed {
            return Err(MarketplaceError::InvalidTransition {
                plugin_id: plugin_id.clone(),
                from: format!("{:?}", record.state),
                to: "CredentialsProvided".to_string(),
            });
        }

        let now = now_ms();
        // Real impl: validate credential shape, store via CredentialService
        let event = MarketplaceEvent::PluginCredentialsProvided {
            plugin_id,
            credential_ids: Vec::new(), // populated by CredentialService
            provided_by,
            at: now,
        };
        Ok(vec![event])
    }

    fn handle_verify_credentials(
        &self,
        plugin_id: String,
        credential_scope_key: Option<CredentialScopeKey>,
        verified_by: OperatorId,
    ) -> Result<Vec<MarketplaceEvent>, MarketplaceError> {
        let record = self
            .records
            .get(&plugin_id)
            .ok_or_else(|| MarketplaceError::PluginNotFound(plugin_id.clone()))?;

        if record.state != MarketplaceState::Installed {
            return Err(MarketplaceError::PluginNotInstalled(plugin_id.clone()));
        }

        let now = now_ms();
        let scope_key =
            credential_scope_key.unwrap_or_else(|| CredentialScopeKey("tenant-default".into()));

        // Real impl: spawns a transient process, runs health check, shuts down.
        // This is an ephemeral action — no persistent state change.
        let event = MarketplaceEvent::PluginCredentialsVerified {
            plugin_id,
            credential_scope_key: scope_key,
            outcome: VerificationOutcome::Ok,
            verified_by,
            at: now,
        };
        Ok(vec![event])
    }

    fn handle_enable(
        &mut self,
        plugin_id: String,
        project: ProjectKey,
        tool_allowlist: Option<Vec<String>>,
        signal_allowlist: Option<Vec<String>>,
        signal_capture_override: Option<SignalCaptureOverride>,
        enabled_by: OperatorId,
    ) -> Result<Vec<MarketplaceEvent>, MarketplaceError> {
        let record = self
            .records
            .get(&plugin_id)
            .ok_or_else(|| MarketplaceError::PluginNotFound(plugin_id.clone()))?;

        if record.state != MarketplaceState::Installed {
            return Err(MarketplaceError::PluginNotInstalled(plugin_id.clone()));
        }

        let now = now_ms();
        let enablement = PluginEnablement {
            plugin_id: plugin_id.clone(),
            project: project.clone(),
            enabled: true,
            enabled_at: now,
            enabled_by: enabled_by.clone(),
            tool_allowlist: tool_allowlist.clone(),
            signal_allowlist: signal_allowlist.clone(),
            signal_capture_override: signal_capture_override.clone(),
        };
        self.enablements
            .insert((plugin_id.clone(), project.clone()), enablement);

        let event = MarketplaceEvent::PluginEnabledForProject {
            plugin_id,
            project,
            enabled_by,
            tool_allowlist,
            signal_allowlist,
            signal_capture_override,
            at: now,
        };
        Ok(vec![event])
    }

    fn handle_disable(
        &mut self,
        plugin_id: String,
        project: ProjectKey,
        disabled_by: OperatorId,
    ) -> Result<Vec<MarketplaceEvent>, MarketplaceError> {
        let key = (plugin_id.clone(), project.clone());
        let enablement = self.enablements.get_mut(&key).ok_or_else(|| {
            MarketplaceError::NotEnabledForProject {
                plugin_id: plugin_id.clone(),
                project: project.clone(),
            }
        })?;

        enablement.enabled = false;

        let now = now_ms();
        let event = MarketplaceEvent::PluginDisabledForProject {
            plugin_id,
            project,
            disabled_by,
            at: now,
        };
        Ok(vec![event])
    }

    fn handle_uninstall(
        &mut self,
        plugin_id: String,
        uninstalled_by: OperatorId,
    ) -> Result<Vec<MarketplaceEvent>, MarketplaceError> {
        let record = self
            .records
            .get(&plugin_id)
            .ok_or_else(|| MarketplaceError::PluginNotFound(plugin_id.clone()))?;

        if record.state == MarketplaceState::Listed {
            return Err(MarketplaceError::InvalidTransition {
                plugin_id: plugin_id.clone(),
                from: "Listed".to_string(),
                to: "Uninstalled".to_string(),
            });
        }

        let now = now_ms();
        let credentials_revoked = record.credential_ids.clone();

        // Disable all project enablements
        let affected_keys: Vec<_> = self
            .enablements
            .keys()
            .filter(|(pid, _)| pid == &plugin_id)
            .cloned()
            .collect();
        for key in affected_keys {
            self.enablements.remove(&key);
        }

        // Transition to Uninstalled
        if let Some(record) = self.records.get_mut(&plugin_id) {
            record.state = MarketplaceState::Uninstalled;
        }

        let event = MarketplaceEvent::PluginUninstalled {
            plugin_id,
            uninstalled_by,
            credentials_revoked,
            at: now,
        };
        Ok(vec![event])
    }
}

// ── Catalog Conversion ──────────────────────────────────────────────────────

/// Convert a catalog TOML entry into a full PluginDescriptor.
pub fn catalog_entry_to_descriptor(entry: CatalogEntry) -> PluginDescriptor {
    let category = match entry.category.as_str() {
        "issue_tracker" => PluginCategory::IssueTracker,
        "chat_ops" => PluginCategory::ChatOps,
        "calendar" => PluginCategory::Calendar,
        "files" => PluginCategory::Files,
        "customer_support" => PluginCategory::CustomerSupport,
        "observability" => PluginCategory::Observability,
        "data_source" => PluginCategory::DataSource,
        "communication_channel" => PluginCategory::CommunicationChannel,
        "eval_scorer" => PluginCategory::EvalScorer,
        other => PluginCategory::Other(other.to_string()),
    };

    let required_credentials = entry
        .required_credentials
        .into_iter()
        .map(|c| CredentialSpec {
            key: c.key,
            display_name: c.display_name,
            kind: match c.kind.as_str() {
                "oauth2" => CredentialKind::OAuth2,
                "api_key" => CredentialKind::ApiKey,
                "app_installation" => CredentialKind::AppInstallation,
                "basic_auth" => CredentialKind::BasicAuth,
                _ => CredentialKind::ApiKey,
            },
            help_url: c.help_url,
            validation: None,
            scope: match c.scope.as_str() {
                "tenant" => CredentialScopeHint::Tenant,
                "workspace" => CredentialScopeHint::Workspace,
                "project" => CredentialScopeHint::Project,
                _ => CredentialScopeHint::Tenant,
            },
            generated: c.generated,
        })
        .collect();

    let post_install_health_check = entry.health_check.map(|hc| HealthCheckSpec {
        method: hc.method,
        timeout_ms: hc.timeout_ms,
        success_criteria: serde_json::Value::Null,
    });

    PluginDescriptor {
        id: entry.id,
        name: entry.name,
        version: entry.version,
        description: entry.description,
        category,
        icon_url: entry.icon_url,
        vendor: entry.vendor,
        command: entry.command,
        tools: entry.tools,
        signal_sources: entry.signal_sources,
        channels: entry.channels,
        required_credentials,
        required_network_egress: entry.network_egress,
        post_install_health_check,
        source: DescriptorSource::BundledCatalog,
        download_url: entry.download_url,
        has_signal_source: entry.has_signal_source,
    }
}

// ── Visibility Filtering (RFC 015 §"Per-Run Tool Visibility") ────────────────

/// RFC 029 amends RFC 015: a small set of built-in tools may now be hidden
/// from the agent prompt depending on visibility context. The set is
/// compile-time closed on purpose — arbitrary built-ins don't become
/// gate-able at a distance.
///
/// `memory_store` is gated by the resolved knowledge provider:
/// `VisibilityContext.resolved_knowledge_provider.ingest_capable == false`
/// hides it. Operators running a retrieval-only provider (e.g. Bedrock KB)
/// see no dangling ingest affordance in the agent's prompt.
pub const GATABLE_BUILTINS: &[&str] = &["memory_store"];

/// Unified visibility check for any tool (plugin-provided or built-in).
///
/// - For a plugin-provided tool (`plugin_id = Some(id)`) the legacy RFC 015
///   allowlist rules apply — plugin enabled + tool on allowlist.
/// - For a built-in tool (`plugin_id = None`) the default is visible; the
///   exception is entries in [`GATABLE_BUILTINS`], which consult the
///   resolved knowledge provider snapshot.
pub fn is_tool_visible(ctx: &VisibilityContext, plugin_id: Option<&str>, tool_name: &str) -> bool {
    match plugin_id {
        Some(pid) => is_plugin_tool_visible(ctx, pid, tool_name),
        None => {
            if GATABLE_BUILTINS.contains(&tool_name) {
                match (tool_name, &ctx.resolved_knowledge_provider) {
                    ("memory_store", Some(snap)) => snap.ingest_capable,
                    // No provider resolved yet → default to visible, matching
                    // the pre-RFC-029 behaviour and cairn-default's
                    // ingest_capable = true posture.
                    ("memory_store", None) => true,
                    _ => true,
                }
            } else {
                true
            }
        }
    }
}

/// Check whether a plugin tool is visible in the given VisibilityContext.
///
/// A tool is visible if:
/// 1. Its plugin is in the context's enabled_plugins set
/// 2. Either the plugin has no tool allowlist (None = all tools visible)
///    or the tool name is in the allowlist
///
/// Built-in cairn tools (not from plugins) are not gated by this function —
/// see [`is_tool_visible`] for the unified check that also covers the
/// `GATABLE_BUILTINS` set.
pub fn is_plugin_tool_visible(ctx: &VisibilityContext, plugin_id: &str, tool_name: &str) -> bool {
    if !ctx.enabled_plugins.contains(plugin_id) {
        return false;
    }
    match ctx.allowlisted_tools.get(plugin_id) {
        Some(Some(allowed)) => allowed.contains(tool_name),
        Some(None) => true, // None = all tools allowed
        None => false,      // plugin not in allowlist map at all
    }
}

/// Check whether a signal type is allowed for a project's enablement.
///
/// A signal type passes if the project's enablement for the source plugin
/// either has no signal_allowlist (None = all signals) or the signal type
/// is in the allowlist.
pub fn is_signal_allowed(enablement: &PluginEnablement, signal_type: &str) -> bool {
    match &enablement.signal_allowlist {
        None => true, // None = all signal types allowed
        Some(list) => list.iter().any(|s| s == signal_type),
    }
}

// ── Signal Knowledge Capture (RFC 015 §"Signal Knowledge Capture") ──────────

/// Resolved capture policy for a signal delivered to a specific project.
///
/// Combines the plugin's declared defaults with the project's per-enablement
/// `SignalCaptureOverride`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ResolvedCapturePolicy {
    /// Whether to project this signal into cairn-graph as a GraphNode(Signal).
    pub graph_project: bool,
    /// Whether to ingest signal payload into cairn-memory.
    pub memory_ingest: bool,
}

/// Resolve the capture policy for a signal in a project.
///
/// Default behaviour (per RFC 015):
/// - graph_project defaults to `true` (cheap, useful for provenance)
/// - memory_ingest defaults to `false` (expensive, opt-in per plugin)
///
/// The plugin descriptor's `has_signal_source` and the per-enablement
/// `SignalCaptureOverride` compose: override takes precedence over default.
pub fn resolve_capture_policy(
    enablement: &PluginEnablement,
    plugin_declares_memory_ingest: bool,
) -> ResolvedCapturePolicy {
    let override_cfg = enablement.signal_capture_override.as_ref();

    let graph_project = override_cfg.and_then(|o| o.graph_project).unwrap_or(true); // default ON

    let memory_ingest = override_cfg
        .and_then(|o| o.memory_ingest)
        .unwrap_or(plugin_declares_memory_ingest); // default from plugin

    ResolvedCapturePolicy {
        graph_project,
        memory_ingest,
    }
}

// ── Errors ──────────────────────────────────────────────────────────────────

/// Marketplace-specific errors.
#[derive(Clone, Debug)]
pub enum MarketplaceError {
    PluginNotFound(String),
    PluginNotInstalled(String),
    InvalidTransition {
        plugin_id: String,
        from: String,
        to: String,
    },
    NotEnabledForProject {
        plugin_id: String,
        project: ProjectKey,
    },
    EvalScorerReserved,
}

impl std::fmt::Display for MarketplaceError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::PluginNotFound(id) => write!(f, "plugin not found: {id}"),
            Self::PluginNotInstalled(id) => write!(f, "plugin not installed: {id}"),
            Self::InvalidTransition {
                plugin_id,
                from,
                to,
            } => write!(
                f,
                "invalid state transition for plugin {plugin_id}: {from} -> {to}"
            ),
            Self::NotEnabledForProject { plugin_id, project } => write!(
                f,
                "plugin {plugin_id} not enabled for project {project:?}"
            ),
            Self::EvalScorerReserved => write!(
                f,
                "EvalScorer capability is reserved for a future RFC; v1 does not support plugin-provided eval scorers"
            ),
        }
    }
}

impl std::error::Error for MarketplaceError {}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use cairn_domain::contexts::PluginCategory;
    use cairn_domain::tenancy::ProjectKey;

    fn test_store() -> Arc<()> {
        Arc::new(())
    }

    fn operator() -> OperatorId {
        OperatorId::new("op-1")
    }

    fn project_p1() -> ProjectKey {
        ProjectKey::new("t1", "w1", "p1")
    }

    fn github_descriptor() -> PluginDescriptor {
        PluginDescriptor {
            id: "github".into(),
            name: "GitHub".into(),
            version: "0.1.0".into(),
            description: Some("GitHub reference plugin".into()),
            category: PluginCategory::IssueTracker,
            icon_url: Some("bundled://github.svg".into()),
            vendor: "cairn".into(),
            command: vec!["cairn-plugin-github".into()],
            tools: vec![
                "github.get_issue".into(),
                "github.list_issues".into(),
                "github.create_pull_request".into(),
            ],
            signal_sources: vec!["github.issue.opened".into(), "github.issue.labeled".into()],
            channels: Vec::new(),
            required_credentials: vec![
                CredentialSpec {
                    key: "github_app_id".into(),
                    display_name: "GitHub App ID".into(),
                    kind: CredentialKind::ApiKey,
                    help_url: None,
                    validation: None,
                    scope: CredentialScopeHint::Tenant,
                    generated: false,
                },
                CredentialSpec {
                    key: "github_app_private_key".into(),
                    display_name: "GitHub App Private Key".into(),
                    kind: CredentialKind::AppInstallation,
                    help_url: None,
                    validation: None,
                    scope: CredentialScopeHint::Tenant,
                    generated: false,
                },
            ],
            required_network_egress: vec!["api.github.com".into()],
            post_install_health_check: Some(HealthCheckSpec {
                method: "github.verify_app_auth".into(),
                timeout_ms: 5000,
                success_criteria: serde_json::json!({"path": "id", "predicate": "greater_than", "value": 0}),
            }),
            source: DescriptorSource::BundledCatalog,
            download_url: Some("https://example.com/cairn-plugin-github".into()),
            has_signal_source: true,
        }
    }

    #[test]
    fn list_then_install_succeeds() {
        let mut svc = MarketplaceService::new(test_store());
        let listed = svc.list_plugin(github_descriptor());
        assert!(matches!(listed, MarketplaceEvent::PluginListed { .. }));

        let events = svc
            .handle_command(MarketplaceCommand::InstallPlugin {
                plugin_id: "github".into(),
                initiated_by: operator(),
            })
            .unwrap();

        assert_eq!(events.len(), 2);
        assert!(matches!(
            &events[0],
            MarketplaceEvent::PluginInstallationStarted { .. }
        ));
        assert!(matches!(
            &events[1],
            MarketplaceEvent::PluginInstalled { .. }
        ));

        let record = svc.get_record("github").unwrap();
        assert_eq!(record.state, MarketplaceState::Installed);
    }

    #[test]
    fn install_unlisted_plugin_fails() {
        let mut svc = MarketplaceService::<()>::new(test_store());
        let result = svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "unknown".into(),
            initiated_by: operator(),
        });
        assert!(matches!(result, Err(MarketplaceError::PluginNotFound(_))));
    }

    #[test]
    fn enable_requires_installed() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());

        let result = svc.handle_command(MarketplaceCommand::EnablePluginForProject {
            plugin_id: "github".into(),
            project: project_p1(),
            tool_allowlist: None,
            signal_allowlist: None,
            signal_capture_override: None,
            enabled_by: operator(),
        });
        assert!(matches!(
            result,
            Err(MarketplaceError::PluginNotInstalled(_))
        ));
    }

    #[test]
    fn enable_disable_lifecycle() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());
        svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "github".into(),
            initiated_by: operator(),
        })
        .unwrap();

        // Enable for project
        let events = svc
            .handle_command(MarketplaceCommand::EnablePluginForProject {
                plugin_id: "github".into(),
                project: project_p1(),
                tool_allowlist: Some(vec!["github.get_issue".into()]),
                signal_allowlist: Some(vec!["github.issue.opened".into()]),
                signal_capture_override: Some(SignalCaptureOverride {
                    graph_project: Some(false),
                    memory_ingest: None,
                }),
                enabled_by: operator(),
            })
            .unwrap();

        assert_eq!(events.len(), 1);
        if let MarketplaceEvent::PluginEnabledForProject {
            tool_allowlist,
            signal_allowlist,
            signal_capture_override,
            ..
        } = &events[0]
        {
            assert_eq!(
                tool_allowlist.as_ref().unwrap(),
                &vec!["github.get_issue".to_string()]
            );
            assert_eq!(
                signal_allowlist.as_ref().unwrap(),
                &vec!["github.issue.opened".to_string()]
            );
            assert_eq!(
                signal_capture_override.as_ref().unwrap().graph_project,
                Some(false)
            );
        } else {
            panic!("expected PluginEnabledForProject");
        }

        // Check enablement query
        let enablement = svc.get_enablement("github", &project_p1()).unwrap();
        assert!(enablement.enabled);

        // Disable
        svc.handle_command(MarketplaceCommand::DisablePluginForProject {
            plugin_id: "github".into(),
            project: project_p1(),
            disabled_by: operator(),
        })
        .unwrap();

        let enablement = svc.get_enablement("github", &project_p1()).unwrap();
        assert!(!enablement.enabled);
    }

    #[test]
    fn uninstall_removes_all_enablements() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());
        svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "github".into(),
            initiated_by: operator(),
        })
        .unwrap();

        // Enable for two projects
        let p1 = project_p1();
        let p2 = ProjectKey::new("t1", "w1", "p2");

        for p in [&p1, &p2] {
            svc.handle_command(MarketplaceCommand::EnablePluginForProject {
                plugin_id: "github".into(),
                project: p.clone(),
                tool_allowlist: None,
                signal_allowlist: None,
                signal_capture_override: None,
                enabled_by: operator(),
            })
            .unwrap();
        }

        assert_eq!(svc.enablements_for_project(&p1).len(), 1);
        assert_eq!(svc.enablements_for_project(&p2).len(), 1);

        // Uninstall
        svc.handle_command(MarketplaceCommand::UninstallPlugin {
            plugin_id: "github".into(),
            uninstalled_by: operator(),
        })
        .unwrap();

        assert_eq!(svc.enablements_for_project(&p1).len(), 0);
        assert_eq!(svc.enablements_for_project(&p2).len(), 0);
        assert_eq!(
            svc.get_record("github").unwrap().state,
            MarketplaceState::Uninstalled
        );
    }

    #[test]
    fn per_project_isolation() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());
        svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "github".into(),
            initiated_by: operator(),
        })
        .unwrap();

        let p1 = project_p1();
        let p2 = ProjectKey::new("t1", "w1", "p2");

        // Enable only for p1
        svc.handle_command(MarketplaceCommand::EnablePluginForProject {
            plugin_id: "github".into(),
            project: p1.clone(),
            tool_allowlist: None,
            signal_allowlist: None,
            signal_capture_override: None,
            enabled_by: operator(),
        })
        .unwrap();

        // p1 sees enablement, p2 does not
        assert_eq!(svc.enablements_for_project(&p1).len(), 1);
        assert_eq!(svc.enablements_for_project(&p2).len(), 0);
    }

    #[test]
    fn descriptor_carries_marketplace_metadata() {
        let desc = github_descriptor();
        assert_eq!(desc.id, "github");
        assert_eq!(desc.category, PluginCategory::IssueTracker);
        assert_eq!(desc.vendor, "cairn");
        assert_eq!(desc.required_credentials.len(), 2);
        assert_eq!(desc.required_credentials[0].key, "github_app_id");
        assert_eq!(
            desc.required_credentials[0].scope,
            CredentialScopeHint::Tenant
        );
        assert!(desc.has_signal_source);
        assert!(desc.post_install_health_check.is_some());
    }

    #[test]
    fn record_holds_descriptor() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());

        let record = svc.get_record("github").unwrap();
        assert_eq!(record.descriptor.id, "github");
        assert_eq!(record.descriptor.tools.len(), 3);
        assert_eq!(record.descriptor.signal_sources.len(), 2);
    }

    #[test]
    fn credential_spec_serde_round_trip() {
        let spec = CredentialSpec {
            key: "test_key".into(),
            display_name: "Test Key".into(),
            kind: CredentialKind::ApiKey,
            help_url: Some("https://example.com/help".into()),
            validation: Some(CredentialValidation::RegexMatch {
                pattern: r"^sk-[a-z0-9]+$".into(),
            }),
            scope: CredentialScopeHint::Project,
            generated: false,
        };
        let json = serde_json::to_string(&spec).unwrap();
        let back: CredentialSpec = serde_json::from_str(&json).unwrap();
        assert_eq!(back.key, "test_key");
        assert_eq!(back.kind, CredentialKind::ApiKey);
        assert_eq!(back.scope, CredentialScopeHint::Project);
    }

    #[test]
    fn load_bundled_catalog_lists_github() {
        let mut svc = MarketplaceService::new(test_store());
        let events = svc.load_bundled_catalog();

        // At least one event (GitHub), all are PluginListed
        assert!(!events.is_empty());
        assert!(events
            .iter()
            .all(|e| matches!(e, MarketplaceEvent::PluginListed { .. })));

        // GitHub is now listed
        let github = svc.get_record("github").expect("github must be listed");
        assert_eq!(github.state, MarketplaceState::Listed);
        assert_eq!(github.descriptor.category, PluginCategory::IssueTracker);
        assert_eq!(github.descriptor.tools.len(), 19);
    }

    #[test]
    fn load_bundled_catalog_idempotent() {
        let mut svc = MarketplaceService::new(test_store());
        let events1 = svc.load_bundled_catalog();
        let events2 = svc.load_bundled_catalog();

        // Second load should not re-list already-known plugins
        assert!(!events1.is_empty());
        assert!(events2.is_empty());
    }

    #[test]
    fn verify_credentials_is_ephemeral() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());
        svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "github".into(),
            initiated_by: operator(),
        })
        .unwrap();

        let events = svc
            .handle_command(MarketplaceCommand::VerifyPluginCredentials {
                plugin_id: "github".into(),
                credential_scope_key: None,
                verified_by: operator(),
            })
            .unwrap();

        assert_eq!(events.len(), 1);
        assert!(matches!(
            &events[0],
            MarketplaceEvent::PluginCredentialsVerified {
                outcome: VerificationOutcome::Ok,
                ..
            }
        ));

        // State unchanged — still Installed, no Connected
        assert_eq!(
            svc.get_record("github").unwrap().state,
            MarketplaceState::Installed
        );
    }

    #[test]
    fn eval_scorer_manifest_rejected_at_install() {
        let mut svc = MarketplaceService::new(test_store());

        // Create a descriptor with EvalScorer category
        let mut desc = github_descriptor();
        desc.id = "eval-scorer-plugin".into();
        desc.category = PluginCategory::EvalScorer;
        svc.list_plugin(desc);

        let result = svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "eval-scorer-plugin".into(),
            initiated_by: operator(),
        });

        assert!(matches!(result, Err(MarketplaceError::EvalScorerReserved)));
    }

    #[test]
    fn build_visibility_context_from_enablements() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());
        svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "github".into(),
            initiated_by: operator(),
        })
        .unwrap();

        let p1 = project_p1();

        // Enable with tool allowlist
        svc.handle_command(MarketplaceCommand::EnablePluginForProject {
            plugin_id: "github".into(),
            project: p1.clone(),
            tool_allowlist: Some(vec!["github.get_issue".into(), "github.list_issues".into()]),
            signal_allowlist: None,
            signal_capture_override: None,
            enabled_by: operator(),
        })
        .unwrap();

        let ctx = svc.build_visibility_context(&p1, Some(RunId::new("run-1")));

        assert!(ctx.enabled_plugins.contains("github"));
        assert_eq!(ctx.enabled_plugins.len(), 1);

        let tools = ctx.allowlisted_tools.get("github").unwrap();
        let tool_set = tools.as_ref().unwrap();
        assert!(tool_set.contains("github.get_issue"));
        assert!(tool_set.contains("github.list_issues"));
        assert!(!tool_set.contains("github.create_pull_request"));
    }

    #[test]
    fn visibility_context_none_allowlist_means_all_tools() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());
        svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "github".into(),
            initiated_by: operator(),
        })
        .unwrap();

        let p1 = project_p1();

        // Enable with no tool allowlist (None = all tools)
        svc.handle_command(MarketplaceCommand::EnablePluginForProject {
            plugin_id: "github".into(),
            project: p1.clone(),
            tool_allowlist: None,
            signal_allowlist: None,
            signal_capture_override: None,
            enabled_by: operator(),
        })
        .unwrap();

        let ctx = svc.build_visibility_context(&p1, None);
        assert!(ctx.enabled_plugins.contains("github"));

        // None means all tools are allowed
        let tools = ctx.allowlisted_tools.get("github").unwrap();
        assert!(tools.is_none());
    }

    #[test]
    fn visibility_context_empty_for_unenabled_project() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());
        svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "github".into(),
            initiated_by: operator(),
        })
        .unwrap();

        let p2 = ProjectKey::new("t1", "w1", "p2");
        let ctx = svc.build_visibility_context(&p2, None);

        assert!(ctx.enabled_plugins.is_empty());
        assert!(ctx.allowlisted_tools.is_empty());
    }

    #[test]
    fn is_plugin_tool_visible_with_allowlist() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());
        svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "github".into(),
            initiated_by: operator(),
        })
        .unwrap();

        svc.handle_command(MarketplaceCommand::EnablePluginForProject {
            plugin_id: "github".into(),
            project: project_p1(),
            tool_allowlist: Some(vec!["github.get_issue".into()]),
            signal_allowlist: None,
            signal_capture_override: None,
            enabled_by: operator(),
        })
        .unwrap();

        let ctx = svc.build_visibility_context(&project_p1(), None);

        // Allowed tool is visible
        assert!(is_plugin_tool_visible(&ctx, "github", "github.get_issue"));
        // Non-allowed tool is not visible
        assert!(!is_plugin_tool_visible(
            &ctx,
            "github",
            "github.create_pull_request"
        ));
        // Tool from a non-enabled plugin is not visible
        assert!(!is_plugin_tool_visible(&ctx, "slack", "slack.send_message"));
    }

    #[test]
    fn is_tool_visible_gates_memory_store_on_resolved_provider() {
        use cairn_domain::events::ResolvedProviderSnapshot;

        let mut ctx = VisibilityContext {
            project: project_p1(),
            run_id: None,
            enabled_plugins: HashSet::new(),
            allowlisted_tools: HashMap::new(),
            resolved_knowledge_provider: None,
        };

        // No resolver yet → memory_store is visible (parity with pre-RFC-029).
        assert!(is_tool_visible(&ctx, None, "memory_store"));

        // Provider reports ingest_capable = true → still visible.
        ctx.resolved_knowledge_provider = Some(ResolvedProviderSnapshot {
            provider_id: "cairn-default".into(),
            ingest_capable: true,
            retrieval_modes: vec!["hybrid".into()],
            scoring_dimensions_surfaced: vec!["semantic_relevance".into()],
        });
        assert!(is_tool_visible(&ctx, None, "memory_store"));

        // Provider reports ingest_capable = false → hidden.
        ctx.resolved_knowledge_provider = Some(ResolvedProviderSnapshot {
            provider_id: "plugin:bedrock-kb".into(),
            ingest_capable: false,
            retrieval_modes: vec!["hybrid".into()],
            scoring_dimensions_surfaced: vec!["semantic_relevance".into()],
        });
        assert!(!is_tool_visible(&ctx, None, "memory_store"));

        // Other built-ins stay visible regardless.
        assert!(is_tool_visible(&ctx, None, "memory_search"));
    }

    #[test]
    fn is_tool_visible_delegates_plugin_tools_to_plugin_check() {
        let mut svc = MarketplaceService::new(test_store());
        svc.list_plugin(github_descriptor());
        svc.handle_command(MarketplaceCommand::InstallPlugin {
            plugin_id: "github".into(),
            initiated_by: operator(),
        })
        .unwrap();
        svc.handle_command(MarketplaceCommand::EnablePluginForProject {
            plugin_id: "github".into(),
            project: project_p1(),
            tool_allowlist: Some(vec!["github.get_issue".into()]),
            signal_allowlist: None,
            signal_capture_override: None,
            enabled_by: operator(),
        })
        .unwrap();

        let ctx = svc.build_visibility_context(&project_p1(), None);
        assert!(is_tool_visible(&ctx, Some("github"), "github.get_issue"));
        assert!(!is_tool_visible(
            &ctx,
            Some("github"),
            "github.create_pull_request"
        ));
    }

    #[test]
    fn is_signal_allowed_with_allowlist() {
        let enablement = PluginEnablement {
            plugin_id: "github".into(),
            project: project_p1(),
            enabled: true,
            enabled_at: 0,
            enabled_by: operator(),
            tool_allowlist: None,
            signal_allowlist: Some(vec![
                "github.issue.opened".into(),
                "github.issue.labeled".into(),
            ]),
            signal_capture_override: None,
        };

        // Allowed signal types pass
        assert!(is_signal_allowed(&enablement, "github.issue.opened"));
        assert!(is_signal_allowed(&enablement, "github.issue.labeled"));
        // Non-allowed signal types are dropped
        assert!(!is_signal_allowed(
            &enablement,
            "github.pull_request.opened"
        ));
    }

    #[test]
    fn is_signal_allowed_none_means_all() {
        let enablement = PluginEnablement {
            plugin_id: "github".into(),
            project: project_p1(),
            enabled: true,
            enabled_at: 0,
            enabled_by: operator(),
            tool_allowlist: None,
            signal_allowlist: None, // None = all signals allowed
            signal_capture_override: None,
        };

        assert!(is_signal_allowed(&enablement, "github.issue.opened"));
        assert!(is_signal_allowed(
            &enablement,
            "github.pull_request.synchronize"
        ));
        assert!(is_signal_allowed(&enablement, "github.rate_limit.warning"));
    }

    // ── Signal Capture Policy Tests ──────────────────────────────────

    #[test]
    fn capture_policy_defaults_graph_on_memory_off() {
        let enablement = PluginEnablement {
            plugin_id: "github".into(),
            project: project_p1(),
            enabled: true,
            enabled_at: 0,
            enabled_by: operator(),
            tool_allowlist: None,
            signal_allowlist: None,
            signal_capture_override: None,
        };

        let policy = resolve_capture_policy(&enablement, false);
        assert!(policy.graph_project); // default ON
        assert!(!policy.memory_ingest); // default OFF (plugin doesn't declare)
    }

    #[test]
    fn capture_policy_plugin_declares_memory_ingest() {
        let enablement = PluginEnablement {
            plugin_id: "github".into(),
            project: project_p1(),
            enabled: true,
            enabled_at: 0,
            enabled_by: operator(),
            tool_allowlist: None,
            signal_allowlist: None,
            signal_capture_override: None,
        };

        let policy = resolve_capture_policy(&enablement, true);
        assert!(policy.graph_project); // still default ON
        assert!(policy.memory_ingest); // ON because plugin declares it
    }

    #[test]
    fn capture_policy_override_disables_both() {
        let enablement = PluginEnablement {
            plugin_id: "github".into(),
            project: project_p1(),
            enabled: true,
            enabled_at: 0,
            enabled_by: operator(),
            tool_allowlist: None,
            signal_allowlist: None,
            signal_capture_override: Some(SignalCaptureOverride {
                graph_project: Some(false),
                memory_ingest: Some(false),
            }),
        };

        // Override takes precedence — both OFF
        let policy = resolve_capture_policy(&enablement, true);
        assert!(!policy.graph_project);
        assert!(!policy.memory_ingest);
    }

    #[test]
    fn capture_policy_override_enables_memory_when_plugin_doesnt() {
        let enablement = PluginEnablement {
            plugin_id: "github".into(),
            project: project_p1(),
            enabled: true,
            enabled_at: 0,
            enabled_by: operator(),
            tool_allowlist: None,
            signal_allowlist: None,
            signal_capture_override: Some(SignalCaptureOverride {
                graph_project: None,       // inherit default (ON)
                memory_ingest: Some(true), // force ON even though plugin says no
            }),
        };

        let policy = resolve_capture_policy(&enablement, false);
        assert!(policy.graph_project); // inherited default
        assert!(policy.memory_ingest); // overridden to ON
    }
}
